name: 3DMOT-Nerf-new
channels:
    - pytorch
    - nvidia
    - conda-forge
    - anaconda
    - pytorch3d
dependencies:
    - python=3.9
    - pip
    - pytorch
    - pytorch-cuda=11.6
    - torchvision>=0.9.1
    - numpy 
    - pytorch3d
    - scipy
    - pip:
        - tqdm
        - opencv-python
        - imageio
        - imageio-ffmpeg
        - matplotlib
        - configargparse
        - wandb
        - git+https://github.com/princeton-vl/lietorch.git

