name: 3DMOT-Nerf
channels:
    - pytorch
    - conda-forge
    - anaconda
dependencies:
    - python=3.9
    - pip
    - numpy
    - pytorch=1.12.0
    - cudatoolkit=11.6
    - torchvision>=0.9.1
    - pip:
        - tqdm
        - opencv-python
        - imageio
        - imageio-ffmpeg
        - matplotlib
        - configargparse
        - wandb


